### ISSUE TITLE
[refresh the page] There is an exception when the lession is released out

### ISSUE THREAD

**Issue by zgxsin** [zgxsin/asvz_lesson_registration#2]
```
The lesson registration is not open, refreshing at 2Hz.
Traceback (most recent call last):
  File "register_for_asvz_lesson.py", line 79, in <module>
    main()
  File "register_for_asvz_lesson.py", line 75, in main
    register_for_asvz_lesson(my_args.id, my_args.frequency)
  File "register_for_asvz_lesson.py", line 62, in register_for_asvz_lesson
    register_button.click()
  File "/home/guzhou/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/guzhou/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "/home/guzhou/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/home/guzhou/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=95.0.4638.69)
```

**Comment by zgxsin** [comment]
This should be addressed by the commit here: 3cb13db205639aadfa93765994e45d4ed8a6de5d. Closing the issue now.
